const favorite_twitter_handles = [
  "@pvl1111",
  "@jamestanton",
  "@stevenstrogatz",
  "@DavidNdii",
  "@freeCodeCamp",
  "@iamdeveloper",
  "@ThePracticalDev",
  "@outreachy",
  "@DevSimplified",
  "@acemarke",
  "@ryanflorence",
  "@kentcdodds",
  "@traversymedia",
  "@youyuxi",
  "@DThompsonDev",
  "@themarcba",
  "@ProfFeynman",
  "@dabit3",
  "@reactnewsletter",
  "@reactjs",
  "@developedbyed",
  "@catalinmpit",
  "@getify",
  "@dan_abramov",
  "@Snowden",
  "@DenzelWashington",
  "@que_tourist",
  "@thenetninjauk",
  "@akol_lam",
  "@davidwalshblog",
  "@LeaVerou",
  "@smashingmag",
  "@jensimmons",
  "@chriscoyier"

];

module.exports = favorite_twitter_handles;
